name: Test

on: workflow_dispatch

env:
  MAJOR: 0
  MINOR: 7
  MAN: 0
  YEAR: 2026
  MESA_V: 26.0.1
  GLEW_V: 2.3.1
  SDL_V: 2.32.10
  SDL_NET_V: 2.2.0

jobs:
  msvc-build:
    if: true
    runs-on: windows-latest
  
    steps:
    - uses: actions/checkout@v4.1.1
    - name: download glew
      uses: suisei-cn/actions-download-file@v1.6.0
      with:
        url: "https://github.com/nigels-com/glew/releases/download/glew-${{ env.GLEW_V }}/glew-${{ env.GLEW_V }}-win32.zip"
        target: .
    - name: Unzip glew
      shell: cmd
      run: |
        7z x -y glew-${{ env.GLEW_V }}-win32.zip
    - name: Download SDL2
      uses: suisei-cn/actions-download-file@v1.6.0
      with:
        url: "https://github.com/libsdl-org/SDL/releases/download/release-${{ env.SDL_V }}/SDL2-devel-${{ env.SDL_V }}-VC.zip"
        target: .
    - name: Download SDL2_net
      uses: suisei-cn/actions-download-file@v1.6.0
      with:
        url: "https://github.com/libsdl-org/SDL_net/releases/download/release-${{ env.SDL_NET_V }}/SDL2_net-devel-${{ env.SDL_NET_V }}-VC.zip"
        target: .
    - name: Unzip SDL2
      shell: cmd
      run: |
        7z x -y SDL2-devel-${{ env.SDL_V }}-VC.zip
    - name: Unzip SDL2_net
      shell: cmd
      run: |
        7z x -y SDL2_net-devel-${{ env.SDL_NET_V }}-VC.zip
    - name: download mesa3d
      uses: suisei-cn/actions-download-file@v1.6.0
      with:
        url: "https://github.com/pal1000/mesa-dist-win/releases/download/${{ env.MESA_V }}/mesa3d-${{ env.MESA_V }}-release-msvc.7z"
        target: .
    - name: Unzip mesa3d
      shell: cmd
      run: |
        7z x -y mesa3d-${{ env.MESA_V }}-release-msvc.7z
        ls
    - run: |
        ren SDL2-${{ env.SDL_V }} sdl2
        ren SDL2_net-${{ env.SDL_NET_V }} sdl2_net
        ren glew-${{ env.GLEW_V }} glew
        ls -R ./
    - uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: 4.0.2
    - name: build
      run: |
        mkdir build
        cd build
        cmake .. -DLIBS_VENDORED=true --fresh
        cmake --build ./
      continue-on-error: true
    - run: |
        cp -r ./build/ CadZinho/
        cp LICENSES.txt CadZinho/
    - name: create archive
      run: 7z a windows_msvc.zip CadZinho
    - name: Upload the result
      uses: actions/upload-artifact@v4.3.0
      with:
        name: msvc
        path: |
          windows_msvc.zip
        retention-days: 5
