name: Translate with AI
# Create translations GUI terms file using AI - Github models
on:
  workflow_dispatch:

permissions:
  models: read

jobs:
  call-model:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Run Lua script
        uses: mileschou/lua-action@master
        with:
          args: |
            luarocks install Lua-cURL
            cd translate
            lua translate_ai.lua
      - name: Generate zip file with results
        run: zip -r translate ./translate
      - name: Upload the result
        uses: actions/upload-artifact@v4.3.0
        with:
          name: translate
          path: translate.zip
          retention-days: 5
